server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # Eureka Server không tự đăng ký vào chính nó
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Tắt bảo vệ tự bảo (môi trường dev)
    enable-self-preservation: false
    # Xoá instance ngay sau 3s nếu không heartbeat (dev nhanh hơn)
    eviction-interval-timer-in-ms: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
